#!/bin/bash

# usage: progress <collection-name>

pages=`cat collections/$1/logs/crawl*.log | grep crawlStatus | jq -r '"\(.details.crawled)/\(.details.total)"' | tail -1`

size=`du -sh collections/$1/ | cut -f 1 -d "	"`

echo "$1: $pages [$size]"
